import turtle
import tkinter
from tkinter import *
from tkinter import ttk
from PIL import Image, ImageTk
import time
def window():
    #First animated Screen
    window=Tk()
    canvas = tkinter.Canvas(master=window,width=1360,height=750)
    canvas.grid(padx=2,pady=2,row=0,column=0,rowspan=10,columnspan=10)
    h=turtle.RawTurtle(canvas)
    h.penup()
    h.hideturtle()
    #filling bg color
    h.speed(12)
    h.goto(-700,400)
    h.pendown()
    h.fillcolor("#008000")
    h.begin_fill()
    for i in range (2):
        h.forward(1400)
        h.right(90)
        h.forward(800)
        h.right(90)
    h.end_fill()
    h.penup()
    #making field
    h.speed(10)
    h.fillcolor("black")
    h.goto(380,240)
    h.pendown()
    h.begin_fill()
    h.circle(-240,180)
    h.forward(750)
    h.circle(-240,180)
    h.forward(750)
    h.end_fill()
    h.penup()
    h.goto(380,200)
    h.pendown()
    h.fillcolor("#945c13")
    h.pencolor("#945c13")
    h.begin_fill()
    h.circle(-200,180)
    h.forward(750)
    h.circle(-200,180)
    h.forward(750)
    h.end_fill()
    h.pencolor("black")
    h.penup()
    h.goto(-200,80)
    h.pendown()
    h.pencolor("black")
    time.sleep(0.8)
    h.write("WELCOME   TO",font=("AR BLANCA",50))
    h.penup()
    h.goto(-440,-100)
    time.sleep(0.8)
    h.pendown()
    h.write("SPORTS FIELD DRAWER",font=("AR BLANCA",70))
    time.sleep(2)
    '''def mainnew(event=None):
        frame1=Frame(window,bg='white',width=1370,height=750).place(x=0,y=0)
        l1=Label(window,text="  Welcome To Sports Field Drawer   ",bg='cadetblue1',fg='blue',font=("algerian",58))
        l1.place(x=0,y=0)
        
        def chgenter(event=None):
            global l
            l.config(fg='purple')
        def chgleave(event=None):
            global l
            l.config(fg='blue')
        def workstart(event=None):
            pass
        def login():
            global l
            Frame(window,bg='white',width=1370,height=750).place(x=0,y=0)
            l1=Label(window,text="Enter Userid",bg='lavender',font=("Forte",30))
            l1.place(x=270,y=150)
            l2=Label(window,text="     Enter Password  ",bg='lavender',font=("Forte",30))
            l2.place(x=270,y=300)
            l3=Label(window,text="                 Login Window                                ",bg= 'cadetblue1',fg='black', font=("lucida calligraphy",60))
            l3.place(x=0,y=0)
            l12=Label(window,text="➜If you want to use without signup\n ➜just click on login",fg='black',bg='lavender',font=("script mt bold",28,'bold'))
            l12.place(x=30,y=590)
            email_text=StringVar()
            e1=Entry(window,bg= 'Orange',font=("Bradley Hand ITC",20),textvariable=email_text)
            e1.place(x=730,y=166)
            password_text=StringVar()
            e2=Entry(window,bg='green',font=("Bradley Hand ITC",20),textvariable=password_text,show='*')
            e2.place(x=730,y=316)
            b1=Button(window,text="Login➥",bg='indianred2',fg='Black',width=15,font=("Stencil",15),command=workstart)
            b1.place(x=400,y=460)
            l=Label(window,text='If you don\'t have account use signup',fg='blue')
            l.place(x=400,y=500)
            l.bind('<Button>',mainnew)
            l.bind('<Enter>',chgenter)
            l.bind('<Leave>',chgleave)
    
        def signup():
             global l
             Frame(window,bg='white',width=1370,height=750).place(x=0,y=0)
             v0=Label(window,text="           Profile Details                                ",fg='black', bg='cadetblue1',font=("lucida calligraphy",35,'bold'))
             v1=Label(window,text="Name ", fg='violetred3',bg='lavender',font=("forte",30))
             v2=Label(window,text="Age", fg='violetred3',bg='lavender',font=("forte",30))
             v3=Label(window,text="Gender", fg='violetred3',bg='lavender',font=("forte",30))
             v4=Label(window,text="State",fg='violetred3',bg='lavender', font=("forte",30))
             v5=Label(window,text="City",fg='violetred3',bg='lavender', font=("forte",30))
             v0.place(x=0,y=0)
             v6=Label(window,text="If you do not want to enter your details, \n you can still use our app by just clicking on submit",fg='Black', bg='lavender',font=("comic Sans MS",20,'bold'))
             v1.place(x=30,y=100)
             v2.place(x=30,y=200)
             v3.place(x=30,y=300)
             v4.place(x=30,y=400)
             v5.place(x=30,y=500)
             v6.place(x=600,y=190)
             name_text=StringVar()
             g1=Entry(window,textvariable=name_text,fg='black',bg='orange',font=("stencil",15))
             g1.place(x=230,y=120)
             age_text=IntVar()
             g2=Entry(window,textvariable=age_text,fg='white',bg='blue',font=("stencil",15))
             g2.place(x=230,y=220)
             city_text=StringVar()
             g5=Entry(window,textvariable=city_text,fg='black',bg='green',font=("stencil",15))
             g5.place(x=230,y=520)
             qpt=IntVar()
             v31=Radiobutton(window,text="Male",fg='black',bg='lavender',variable=qpt,value=1,font=("script mt bold",18))
             v31.place(x=230,y=300)
             v32=Radiobutton(window,text="Female",fg='black',bg='lavender',variable=qpt,value=2,font=("script mt bold",18))
             v32.place(x=390,y=300)
             vip=Button(window,text="Next",width=25,bg= 'indianred2',fg='black',font=("Stencil",18), command=workstart)
             vip.place(x=490,y=580)
             OPTIONS = [
                 "Andhra Pradesh"
                 ,"Arunachal Pradesh"
                 ,"Assam"
                 ,"Bihar"
                 ,"Chhattisgarh"
                 ,"delhi"
                 ,'Goa '
                 ,'Gujarat '
                 ,' Himachal Pradesh Shimla'
                 ,'Jammu and Kashmir '
                 ,'Jharkhand '
                 ,'Karnataka '
                  ,'Kerala '
                  ,' Madhya Pradesh '
                  ,' Maharashtra '
                 ,'Manipur '
                  ,' Meghalaya '
                  ,' Mizoram '
                  , 'Nagaland '
                  ,'Odisha'
                  ,'Punjab'
                  ,' Rajasthan'
                  ,'Sikkim '
                  ,' Tamil Nadu '
                  ,'Tripura'
                  ,'Uttar Pradesh'
                  ,'West Bengal '
                 ] #etc
             variable = StringVar(window)
             variable.set(OPTIONS[0]) # default value
             w = OptionMenu(window,variable, *OPTIONS)
             w.place(x=230,y=400)
             w.configure(bd=25,bg='skyblue')
             l=Label(window,text='Already have aacount use login',fg='blue')
             l.place(x=400,y=500)
             l.bind('<Button>',mainnew)
             l.bind('<Enter>',chgenter)
             l.bind('<Leave>',chgleave)
        b1=Button(window,text="Login",width=20,bg= 'Orange',font=("Stencil",18),command=login)
        b1.place(x=450,y=179)
        b2=Button(window,text="Signup",width=20,bg= 'lightgreen',font=("Stencil",18), command=signup)
        b2.place(x=450,y=285)
        l5=Label(window,text="Instructions:",fg='blue',bg='lavender',font=("comic Sans MS",30,'bold'))
        l5.place(x=100,y=360)
        l8=Label(window,text="➜If account Created , click on login!",fg='black',bg='lavender',font=("Berlin sans FB",20))
        l8.place(x=100,y=410)
        l10=Label(window,text="➜If account not Created , click on signup!",fg='brown',bg='lavender',font=("Berlin sans FB",20))
        l10.place(x=100,y=460)
        l12=Label(window,text="➜If you want to use without signup\n ➜just click on login",fg='black',bg='lavender',font=("Berlin sans FB",20))
        l12.place(x=100,y=510)
        
        
        
    h.clear()
    mainnew()'''
    
    #main screen
    image = Image.open("ground.png")
    image=image.resize((1360, 700), Image.LANCZOS)
    test = ImageTk.PhotoImage(image)
    label1 = ttk.Label(image=test)
    label1.image = test
    label1.place(x=0,y=0)
    def clicked(x,y):
        turtle.bye()
        turtle.update()
    def football():
        q = turtle.Screen()
        q.setup(width=1357,height=760)
        q.bgcolor("#945c13")
        t=turtle.Turtle()
        t.speed(5)
        t.fillcolor("#136307")
        t.pensize(5)
        t.begin_fill()
        t.penup()
        t.goto(-550,-250)
        t.pendown()
        t.left(90)
        t.forward(500)
        t.right(90)
        t.forward(1100)
        t.right(90)
        t.forward(500)
        t.right(90)
        t.forward(1100)
        t.end_fill()
        t.penup()
        t.goto(-500,200)
        t.pencolor("white")
        t.pendown()
        t.right(180)
        t.pensize(8)
        for i in range(2):
            t.forward(1000)
            t.right(90)
            t.forward(400)
            t.right(90)
        t.pensize(5)
        for i in range(10):
            t.fillcolor("#103b0b")
            t.begin_fill()
            t.forward(50)
            t.right(90)
            t.forward(400)
            t.right(90)
            t.forward(50)
            t.end_fill()
            t.right(180)
            t.penup()
            t.forward(50)
            t.pendown()
            t.fillcolor("#108004")
            t.begin_fill()
            t.forward(50)
            t.left(90)
            t.forward(400)
            t.left(90)
            t.forward(50)
            t.end_fill()
            t.right(180)
            t.penup()
            t.forward(50)
            t.pendown()
        t.penup()
        t.goto(0,200)
        t.right(90)
        t.pendown()
        t.pensize(8)
        t.forward(400)
        t.penup()
        t.pensize(5)
        t.goto(-400,60)
        t.right(90)
        t.pendown()
        r=60
        t.circle(r)
        t.penup()
        t.left(90)
        t.goto(-500,100)
        t.pendown()
        t.fillcolor("#136307")
        t.begin_fill()
        t.left(90)
        t.forward(120)
        t.right(90)
        t.forward(200)
        t.right(90)
        t.forward(120)
        t.right(90)
        t.forward(200)
        t.end_fill()
        t.right(180)
        t.forward(160)
        t.left(90)
        t.forward(40)
        t.left(90)
        t.fillcolor("#b5babd")
        t.begin_fill()
        t.forward(120)
        t.left(90)
        t.forward(40)
        t.left(90)
        t.forward(120)
        t.penup()
        t.end_fill()
        t.goto(400,60)
        t.right(90)
        t.pendown()
        r=60
        t.circle(r)
        t.penup()
        t.goto(500,100)
        t.pendown()
        t.fillcolor("#136307")
        t.begin_fill()
        t.forward(120)
        t.left(90)
        t.forward(200)
        t.left(90)
        t.forward(120)
        t.left(90)
        t.forward(200)
        t.left(180)
        t.forward(160)
        t.right(90)
        t.end_fill()
        t.fillcolor("#b5babd")
        t.begin_fill()
        t.forward(40)
        t.right(90)
        t.forward(120)
        t.right(90)
        t.forward(40)
        t.end_fill()
        t.penup()
        t.goto(0,-80)
        t.pendown()
        t.pensize(8)
        r=80
        t.circle(r)
        t.penup()
        t.goto(-385,255)
        t.pendown()
        t.pencolor("black")
        t.write("FOOTBALL COURT",font=("AR DARLING",65))
        t.speed(13)
        a=-620
        b=150
        c=-570
        d=200
        e=186
        f=-605
        g=152
        h=-666
        j=-635
        k=245
        l=-574
        m=213
        for i in range(4):
            t.penup()
            t.fillcolor("white")
            r=50
            t.goto(a,b)
            t.pendown()
            t.begin_fill()
            t.circle(r)
            t.end_fill()
            t.penup()
            t.goto(a,b)
            t.pendown()
            t.left(90)
            t.forward(100)
            t.penup()
            t.goto(c,d)
            t.pendown()
            t.left(90)
            t.forward(100)
            t.penup()
            t.right(180)
            t.fillcolor("black")
            t.goto(a,e)
            t.begin_fill()
            t.pendown()
            r=15
            t.circle(r)
            t.end_fill()
            t.left(90)
            t.penup()
            t.goto(f,g)
            t.begin_fill()
            t.pendown()
            t.circle(15,180)
            t.end_fill()
            t.penup()
            t.goto(h,e)
            t.begin_fill()
            t.pendown()
            t.left(90)
            t.circle(15,180)
            t.end_fill()
            t.penup()
            t.goto(j,k)
            t.pendown()
            t.begin_fill()
            t.left(90)
            t.circle(15,180)
            t.end_fill()
            t.penup()
            t.goto(l,m)
            t.pendown()
            t.begin_fill()
            t.left(90)
            t.circle(15,180)
            t.end_fill()
            b-=150
            d-=150
            e-=150
            g-=150
            k-=150
            m-=150
        t.speed(15)
        a=620
        b=150
        c=670
        d=200
        e=186
        f=635
        g=152
        h=573
        j=605
        k=245
        l=666
        m=213
        for i in range(4):
            t.penup()
            t.fillcolor("white")
            r=50
            t.goto(a,b)
            t.pendown()
            t.begin_fill()
            t.circle(r)
            t.end_fill()
            t.penup()
            t.goto(a,b)
            t.pendown()
            t.left(90)
            t.forward(100)
            t.penup()
            t.goto(c,d)
            t.pendown()
            t.left(90)
            t.forward(100)
            t.penup()
            t.right(180)
            t.fillcolor("black")
            t.goto(a,e)
            t.begin_fill()
            t.pendown()
            r=15
            t.circle(r)
            t.end_fill()
            t.left(90)
            t.penup()
            t.goto(f,g)
            t.begin_fill()
            t.pendown()
            t.circle(15,180)
            t.end_fill()
            t.penup()
            t.goto(h,e)
            t.begin_fill()
            t.pendown()
            t.left(90)
            t.circle(15,180)
            t.end_fill()
            t.penup()
            t.goto(j,k)
            t.pendown()
            t.begin_fill()
            t.left(90)
            t.circle(15,180)
            t.end_fill()
            t.penup()
            t.goto(l,m)
            t.pendown()
            t.begin_fill()
            t.left(90)
            t.circle(15,180)
            t.end_fill()
            b-=150
            d-=150
            e-=150
            g-=150
            k-=150
            m-=150
        from plyer import notification
        notification.notify(
            title="Field drawer",
            message="Please clik anywhere to back",
            app_icon="favicon.ico",
        timeout=5
        )
        turtle.onscreenclick(clicked)
    def badminton():
        q=turtle.Screen()
        q.bgcolor("#008000")
        q.setup(width=1357,height=760)
        h=turtle.Turtle()
        h.hideturtle()
        h.penup()
        h.pensize(5)
        h.pencolor("black")
        h.backward(500)
        h.left(90)
        h.forward(200)
        h.right(90)
        h.showturtle()           
        h.pendown()
        h.forward(1000)
        h.right(90)
        h.forward(400)
        h.right(90)
        h.forward(1000)
        h.right(90)
        h.forward(400)
        h.penup()
        h.right(90)
        h.forward(500)
        h.right(90)
        h.pendown()
        h.forward(400)
        h.penup()
        h.goto(-540,90)
        h.backward(150)
        h.pendown()
        h.forward(480)
        h.left(90)
        h.forward(1080)
        h.left(90)
        h.forward(480)
        h.left(90)
        h.forward(1080)
        h.left(90)
        h.forward(240)
        h.left(90)
        h.forward(350)
        h.left(90)
        h.forward(240)
        h.left(180)
        h.forward(480)
        h.left(90)
        h.forward(380)
        h.left(90)
        h.forward(480)
        h.left(180)
        h.forward(240)
        h.left(90)
        h.forward(350)
        h.left(180)
        h.forward(1080)
        h.left(180)
        h.forward(40)
        h.left(90)
        h.forward(240)
        h.left(180)
        h.forward(480)
        h.left(90)
        h.forward(500)
        h.left(90)
        h.pensize(10)
        h.forward(480)
        h.left(90)
        h.pencolor("black")
        h.pensize(5)
        h.forward(540)
        h.left(90)
        h.forward(40)
        h.left(90)
        h.forward(1080)
        h.left(90)
        h.forward(40)
        h.left(90)
        h.forward(40)
        h.left(90)
        h.forward(480)
        h.left(90)
        h.forward(40)
        h.left(90)
        h.forward(40)
        h.left(90)
        h.forward(1080)
        h.penup()
        h.goto(-280,260)
        h.pendown()
        h.write("Badminton court",font=("AR DARLING",50))
        from plyer import notification
        notification.notify(
            title="Field drawer",
            message="Please clik anywhere to back",
            app_icon="favicon.ico",
        timeout=5
        )
        turtle.onscreenclick(clicked)
    def basketball():
        import turtle
        q=turtle.Screen()
        q.bgcolor("#eb8c34")
        q.setup(width=1357,height=760)
        h=turtle.Turtle()
        h.hideturtle()
        h.penup()
        h.backward(500)
        h.left(90)
        h.forward(200)
        h.right(90)
        h.showturtle()
        h.pensize(7)
        h.pendown()
        h.pencolor("white")
        h.fillcolor("blue")
        h.begin_fill()
        h.forward(1000)
        h.right(90)
        h.forward(500)
        h.right(90)
        h.forward(1000)
        h.right(90)
        h.forward(500)
        h.end_fill()
        h.penup()
        h.backward(450)
        h.right(90)
        h.pendown()
        h.circle(200,180)
        h.left(90)
        h.forward(150)
        h.left(90)
        h.fillcolor("#ed2d05")
        h.begin_fill()
        h.forward(150)
        h.circle(-40)
        h.right(90)
        h.forward(80)
        h.right(90)
        h.forward(150)
        h.end_fill()
        h.penup()
        h.right(90)
        h.forward(70)
        h.right(90)
        h.forward(30)
        h.pendown()
        h.right(90)
        h.forward(30)
        h.circle(10)
        h.forward(30)
        h.penup()
        h.hideturtle()
        h.right(90)
        h.forward(30)
        h.right(90)
        h.forward(271)
        h.right(90)
        h.forward(500)
        h.right(90)
        h.showturtle()
        h.pendown()
        h.forward(500)
        h.hideturtle()
        h.penup()
        h.left(90)
        h.forward(500)
        h.left(90)
        h.forward(50)
        h.left(90)
        h.pendown()
        h.showturtle()
        h.circle(-200,180)
        h.right(90)
        h.forward(150)
        h.right(90)
        h.fillcolor("#ed2d05")
        h.begin_fill()
        h.forward(150)
        h.circle(40)
        h.left(90)
        h.forward(80)
        h.left(90)
        h.forward(150)
        h.end_fill()
        h.penup()
        h.hideturtle()
        h.left(90)
        h.forward(70)
        h.left(90)
        h.forward(30)
        h.pendown()
        h.showturtle()
        h.left(90)
        h.forward(30)
        h.circle(-10)
        h.forward(30)
        h.penup()
        h.hideturtle()
        h.left(90)
        h.forward(30)
        h.left(90)
        h.forward(270)
        h.left(90)
        h.forward(500)
        h.left(90)
        h.forward(350)
        h.showturtle()
        h.pendown()
        h.left(90)
        h.begin_fill()
        h.circle(100,180)
        h.circle(100,180)
        h.end_fill()
        h.penup()
        h.goto(0,200)
        h.right(90)
        h.pensize(10)
        h.pendown()
        h.forward(500)
        h.penup()
        h.goto(-300,240)
        h.pendown()
        h.write("BASKETBALL COURT",font=("AR DARLING",50))
        from plyer import notification
        notification.notify(
            title="Field drawer",
            message="Please clik anywhere to back",
            app_icon="favicon.ico",
        timeout=5
        )
        turtle.onscreenclick(clicked)
    def no():
        window.destroy()
    #main screen button
    W1=Button(window,text="   Football Court    ",font=("Stencil",14),bg=("#945c13"), command=football)
    W1.place(x=309,y=330)
    image1 = Image.open("football.jpeg")
    image1=image1.resize((200, 150), Image.LANCZOS)
    test1 = ImageTk.PhotoImage(image1)
    W2 = Button(window,image=test1, command=football)
    W2.place(x=310,y=175)
    image2 = Image.open("basketball.jpg")
    image2=image2.resize((200, 150), Image.LANCZOS)
    test2 = ImageTk.PhotoImage(image2)
    W3=Button(window,text="Basketball Court ",font=("Stencil",14),bg=("#945c13"), command=basketball)
    W3.place(x=860,y=330)
    W4=Button(window,image=test2,command=basketball)
    W4.place(x=860,y=175)
    image3 = Image.open("badminton.jpg")
    image3=image3.resize((200, 150), Image.LANCZOS)
    test3 = ImageTk.PhotoImage(image3)
    W5=Button(window,text=" Badminton Court  ",font=("Stencil",14),bg=("#945c13"), command=badminton)
    W5.place(x=585.5,y=330)
    W6=Button(window,image=test3, command=badminton)
    W6.place(x=586,y=368)
    W7=Button(window,text=" exit  ",width=65,font=("Stencil",14),bg=("#008000"), command=no)
    W7.place(x=300,y=600)
    window.mainloop()
window()
